name: Test

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.11"
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install Dependencies
        run: |
          uv sync
          corepack enable
          pnpm install
          make build
      - run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
